all:
  vars:
    ansible_user: "" # REPLACE WITH USERNAME
    ansible_password: "" # REPLACE WITH PASSWORD
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    home_dir: "" # REPLACE WITH USER HOME DIRECTORY PATH
    competition: "" # REPLACE WITH COMPETITION NAME (Options: EmpireStateHealth, IRSEC, UBLockdown)
  children:
    windowsServer:
      hosts:
        # REPLACE WITH WINDOWS SERVER IP ADDRESSES
    windows10:
      hosts:
        # REPLACE WITH WINDOWS 10 IP ADDRESSES