all:
  vars:
    home_dir: "/home/ubuntu" # REPLACE WITH USER HOME DIRECTORY PATH
    competition: "ISTSQuals" # REPLACE WITH COMPETITION NAME (Options: EmpireStateHealth, IRSEC, UBLockdown, ISTSQuals)
  children:
    windows:
      vars:
        ansible_user: "fathertime" # REPLACE WITH USERNAME
        ansible_password: "Change.me123!" # REPLACE WITH PASSWORD
        ansible_connection: winrm
        ansible_port: 5985
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
      children:
        windowsServer:
          hosts:
            192.168.1.1:
            192.168.1.2:
            192.168.1.3:
        windows10:
          hosts:
            192.168.1.6:
    linux:
      vars:
        ansible_user: "ubuntu" # REPLACE WITH USERNAME
        ansible_password: "ubuntu" # REPLACE WITH PASSWORD
        ansible_become_password: "ubuntu" # REPLACE WITH PASSWORD
        ansible_become_method: sudo
        ansible_connection: ssh
        ansible_port: 22
      hosts:
        192.168.1.7:
    freebsd:
      vars:
        ansible_user: "admin" # REPLACE WITH USERNAME
        ansible_password: "pfsense" # REPLACE WITH PASSWORD
        ansible_become_password: "pfsense" # REPLACE WITH PASSWORD
        ansible_become_method: su
        ansible_connection: ssh
        ansible_port: 22
      hosts:
        192.168.1.254: