---
- name: Deploy Mirage Windows Server
  hosts: windowsServer
  roles:
    - windowsServer
  tags:
    - deploy
    - windows
    - windowsServer
    - never

- name: Deploy Mirage Windows 10
  hosts: windows10
  roles:
    - windows10
  tags:
    - deploy
    - windows
    - windows10
    - never

- name: Deploy Mirage Linux
  hosts: linux
  become: yes
  roles:
    - linux
  tags:
    - deploy
    - linux
    - never

- name: Deploy Mirage FreeBSD/pfSense
  hosts: freebsd
  become: yes
  roles:
    - freebsd
  tags:
    - deploy
    - freebsd
    - pfsense
    - never