---
- name: Undeploy Mirage Windows Server
  hosts: windowsServer
  roles:
    - undeploy
  tags:
    - undeploy
    - windows
    - windowsServer
    - never

- name: Undeploy Mirage Windows 10
  hosts: windows10
  roles:
    - undeploy
  tags:
    - undeploy
    - windows
    - windows10
    - never

# ISNT IMPLEMENTED YET
# - name: Undeploy Mirage Linux
#   hosts: linux
#   become: yes
#   roles:
#     - undeploy
#   tags:
#     - undeploy
#     - linux
#     - never

# - name: Undeploy Mirage FreeBSD
#   hosts: freebsd
#   become: yes
#   roles:
#     - undeploy
#   tags:
#     - undeploy
#     - freebsd
#     - pfsense
#     - never