---
- name: Deploy Mirage Windows Server
  hosts: windowsServer
  roles:
    - windowsServer
  tags:
    - windows
    - windowsServer
    - never

- name: Deploy Mirage Windows 10
  hosts: windows10
  roles:
    - windows10
  tags:
    - windows
    - windows10
    - never
